# Zurg configuration version
zurg: v1

token: Real-Debrid API Token # 
port: 9999
concurrent_workers: 10
check_for_changes_every_secs: 10
info_cache_time_hours: 12
enable_repair: true # BEWARE! THERE CAN ONLY BE 1 INSTANCE OF ZURG THAT SHOULD REPAIR YOUR TORRENTS
on_library_update:
network_buffer_size: 32768
# List of directory definitions and their filtering rules
directories:
torrents:
group: 1 # notice the group now is "all", which means it will have all the torrents of shows+movies combined because this directory is alone in this group
filters:
- regex: /.*/
